import { NgModule } from '@angular/core';

import {
  AggregateService,
  ColumnChooserService,
  ColumnMenuService,
  EditService as GridEditService,
  ExcelExportService,
  FilterService,
  GridModule,
  GroupService,
  PageService,
  PdfExportService,
  ResizeService,
  RowDDService,
  SortService,
  ToolbarService as GridToolbarService,
} from '@syncfusion/ej2-angular-grids';
import { ContextMenuModule, TabModule, ToolbarModule, TreeViewModule } from '@syncfusion/ej2-angular-navigations';
import {
  AccumulationAnnotationService,
  AccumulationChartModule,
  AccumulationDataLabelService,
  AccumulationLegendService,
  AccumulationTooltipService,
  AreaSeriesService,
  CategoryService,
  ChartModule,
  ColumnSeriesService,
  DataLabelService,
  DateTimeService,
  ExportService,
  LegendService,
  LineSeriesService,
  PieSeriesService,
  PolarSeriesService,
  PyramidSeriesService,
  RangeNavigatorModule,
  RangeTooltipService,
  SplineAreaSeriesService,
  StackingColumnSeriesService,
  StackingLineSeriesService,
  TooltipService,
} from '@syncfusion/ej2-angular-charts';
import {
  ComboBoxModule,
  DropDownListAllModule,
  DropDownListModule,
  DropDownTreeModule,
  MultiSelectAllModule,
  MultiSelectModule,
} from '@syncfusion/ej2-angular-dropdowns';
import { DropDownButtonModule, SplitButtonModule } from '@syncfusion/ej2-angular-splitbuttons';
import {
  AgendaService,
  DayService,
  MonthAgendaService,
  MonthService,
  ScheduleModule,
  WeekService,
  WorkWeekService,
} from '@syncfusion/ej2-angular-schedule';
import { CalendarModule, DatePickerModule, DateRangePickerModule } from '@syncfusion/ej2-angular-calendars';
import { DashboardLayoutModule } from '@syncfusion/ej2-angular-layouts';
import {
  ColorPickerModule,
  NumericTextBoxModule,
  SliderModule,
  TextBoxAllModule,
  TextBoxModule,
  UploaderModule,
} from '@syncfusion/ej2-angular-inputs';
import { ButtonAllModule, ButtonModule, CheckBoxModule, RadioButtonAllModule } from '@syncfusion/ej2-angular-buttons';
import { KanbanModule } from '@syncfusion/ej2-angular-kanban';
import {
  DocumentEditorAllModule,
  DocumentEditorContainerAllModule,
  DocumentEditorContainerModule,
  DocumentEditorModule,
  EditorService,
  PrintService as DocPrintService,
  SearchService,
  SelectionService,
  ToolbarService as DocToolbarService,
} from '@syncfusion/ej2-angular-documenteditor';
import { InPlaceEditorAllModule } from '@syncfusion/ej2-angular-inplace-editor';
import {
  HtmlEditorService,
  ImageService,
  LinkService,
  RichTextEditorModule,
  ToolbarService as RTEToolbarService,
} from '@syncfusion/ej2-angular-richtexteditor';
import { ListViewAllModule, ListViewModule } from '@syncfusion/ej2-angular-lists';
import { ProgressBarModule } from '@syncfusion/ej2-angular-progressbar';
import { SpreadsheetAllModule } from '@syncfusion/ej2-angular-spreadsheet';
import { DialogModule, TooltipModule } from '@syncfusion/ej2-angular-popups';
import {
  AnnotationService,
  BookmarkViewService,
  FormFieldsService,
  LinkAnnotationService,
  MagnificationService,
  NavigationService,
  PdfViewerAllModule,
  PdfViewerModule,
  PrintService as PdfPrintService,
  TextSearchService,
  TextSelectionService,
  ThumbnailViewService,
  ToolbarService as PdfToolbarService,
} from '@syncfusion/ej2-angular-pdfviewer';

@NgModule({
  exports: [
    AccumulationChartModule,
    ButtonAllModule,
    ButtonModule,
    CalendarModule,
    ChartModule,
    CheckBoxModule,
    ColorPickerModule,
    ComboBoxModule,
    ContextMenuModule,
    DashboardLayoutModule,
    DatePickerModule,
    DateRangePickerModule,
    DialogModule,
    DocumentEditorAllModule,
    DocumentEditorContainerAllModule,
    DocumentEditorContainerModule,
    DocumentEditorModule,
    DropDownButtonModule,
    DropDownListAllModule,
    DropDownListModule,
    DropDownTreeModule,
    GridModule,
    InPlaceEditorAllModule,
    KanbanModule,
    ListViewAllModule,
    ListViewModule,
    MultiSelectAllModule,
    MultiSelectModule,
    NumericTextBoxModule,
    PdfViewerAllModule,
    PdfViewerModule,
    ProgressBarModule,
    RadioButtonAllModule,
    RangeNavigatorModule,
    RichTextEditorModule,
    SliderModule,
    SplitButtonModule,
    SpreadsheetAllModule,
    TabModule,
    TextBoxAllModule,
    TextBoxModule,
    ToolbarModule,
    TooltipModule,
    TreeViewModule,
    UploaderModule,
  ],
  declarations: [],
  providers: [
    AccumulationAnnotationService,
    AccumulationDataLabelService,
    AccumulationLegendService,
    AccumulationTooltipService,
    AggregateService,
    AgendaService,
    AnnotationService,
    AreaSeriesService,
    BookmarkViewService,
    CategoryService,
    ColumnChooserService,
    ColumnMenuService,
    ColumnSeriesService,
    DataLabelService,
    DateTimeService,
    DayService,
    DocPrintService,
    DocToolbarService,
    EditorService,
    ExportService,
    FilterService,
    FormFieldsService,
    GridEditService,
    GridToolbarService,
    GroupService,
    HtmlEditorService,
    ImageService,
    LegendService,
    LineSeriesService,
    LinkAnnotationService,
    LinkService,
    MagnificationService,
    MonthAgendaService,
    MonthService,
    NavigationService,
    PageService,
    PdfPrintService,
    PdfToolbarService,
    PieSeriesService,
    PolarSeriesService,
    PyramidSeriesService,
    RangeTooltipService,
    ResizeService,
    RowDDService,
    RTEToolbarService,
    SearchService,
    SelectionService,
    SortService,
    SplineAreaSeriesService,
    StackingColumnSeriesService,
    StackingLineSeriesService,
    TextSearchService,
    TextSelectionService,
    ThumbnailViewService,
    TooltipService,
    WeekService,
    WorkWeekService,
  ],
})
export class AppSyncfusionModule {}
